version: '3.8'

services:

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - todolist_2_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'


volumes:
  todolist_2_data:
