version: '3.9'

services:


  bot:
    image: ${DOCKERHUB_USER}/todolist_2:latest
    env_file: .env
    environment:
      DB_HOST: db
#    dns: 8.8.8.8
    depends_on:
      db:
        condition: service_healthy
      run_migrations:
        condition: service_completed_successfully
    volumes:
      - ./bot:/opt/app/bot/
    command:
      - python3
      - manage.py
      - run_bot


  frontend:
    image: sermalenk/skypro-front:lesson-38
    restart: on-failure
    ports:
      - '80:80'
    depends_on:
      api:
        condition: service_started
      collect_static:
        condition: service_completed_successfully
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/


  api:
    image: ${DOCKERHUB_USER}/todolist_2:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      run_migrations:
        condition: service_completed_successfully


  run_migrations:
    image: ${DOCKERHUB_USER}/todolist_2:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate


  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 5s
      interval: 3s
      retries: 10
    volumes:
      - todolist_2_pg_data:/var/lib/postgresql/data/


  collect_static:
    image: ${DOCKERHUB_USER}/todolist_2:latest
    env_file: .env
    command: python manage.py collectstatic -c --no-input
    volumes:
      - django_static:/opt/app/static/


volumes:
  todolist_2_pg_data:
  django_static: